#!/usr/bin/env python2.7

adress=['8.8.4.4', '1.1.1.1-3', '172.21.41.128-172.21.41.132']
def ping_adresses(adresses):
    import subprocess
    import ipaddress
    final=[]
    final1=[]
    final2=[]

    for ip in adresses:
        try:
            ipaddress.ip_address(ip)
        except ValueError:
            ip.split('-')
            j=ip[1]
            print(j)
        else:
            final.append(ip)
            print(final)
    result=final+finel1+finel2


            
            
print(ping_adresses(adress))
        
    
